channels:
  - nvidia/label/cuda-11.7.0
  - pytorch
  - conda-forge

package:
  name: warp
  version: 2.0.0dev0

# source:
#   url: https://github.com/warpem/warp/archive/refs/tags/v{{ version }}.tar.gz
#   sha256: 2639a8c95b7a0276587582b369dcc96340ec0c941aa04662e430a4287ba839e9

source:
  path: ../

build:
  number: 0

requirements:
  host:
    - python
    - torchvision
    - libtiff
    - pytorch-cuda=11.7
    - pytorch=2.0.1
    - fftw
    - cxx-compiler=1.3
    - dotnet=8.0
    - cuda-toolkit
    - mkl=2024.0.0
    - cmake
  run:
    - python
    - torchvision
    - libtiff
    - pytorch-cuda=11.7
    - pytorch=2.0.1
    - fftw
    - cxx-compiler=1.3
    - dotnet=8.0
    - cuda-toolkit
    - mkl=2024.0.0
    - cmake

test:
  commands:
    - WarpTools --help

about:
  home: http://www.warpem.com
  summary: 'Advanced cryo-EM data processing'
  description: |
    Warp is a set of tools for cryo-EM and cryo-ET data processing including, 
    among other tools: Warp, M, WarpTools, MTools, MCore, and Noise2Map.
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.txt
  doc_url: http://warpem.com
  dev_url: https://github.com/warpem/warp

extra:
  recipe-maintainers:
    - dtegunov
    - alisterburt
