name: Packaging (conda)

### TEMP FOR TESTING
on:
  push:  # This triggers the workflow on push events to any branch
###

#on:
#  push:
#    branches:
#      - main
#    tags:
#      # push a tagged commit to trigger a release...
#      # e.g. git tag -am v0.0.1 "v0.0.1"; git push --follow-tags
#      - "v*"

# cancel in-progress runs that use the same workflow and branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    ### COMMENTED OUT FOR TESTING
#    if: success() && startsWith(github.ref, 'refs/tags/') && github.event_name != 'schedule'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Mamba
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.10"
          miniforge-version: latest
          channels: conda-forge, nodefaults  # channels for installing mamba only
      - name: Build Conda Package
        run: |
          conda install conda-build anaconda-client
          conda build conda-recipe -c nvidia/label/cuda-11.7.0 -c pytorch -c conda-forge
          
