# This workflow installs mkdocs-material and itsdependencies, 
# builds the docs, and pushes the built site to the `gh-pages` branch 
# of the warpem.github.io repository.
name: docs

on:
  push:
    branches:
      - main

jobs:
  deploy-docs:
    permissions:
      contents: write
      
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install mkdocs-material

      # Build the docs
      - name: Build the docs
        run: |
          mkdocs build

      # Push the site to the gh-pages branch of warpem/warpem.github.io
      # this means the site will be available at warpem.github.io 
      # rather than warpem.github.io/warp
      - name: 🚢 Deploy site
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: warpem/warpem.github.io
          publish_dir: ./site
